services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: financetracker_backend
        ports:
            - "12345:7777"
        environment:
            DATABASE_URL: financetracker_db:3306/${MYSQL_DATABASE}
            DATABASE_USERNAME: ${MYSQL_USER}
            DATABASE_PASSWORD: ${MYSQL_PASSWORD}
        depends_on:
            financetracker_db:
                condition: service_healthy
        networks:
            - financetracker_backend

    financetracker_db:
        image: mysql:8.0
        container_name: financetracker_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - financetracker_backend
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-p${MYSQL_ROOT_PASSWORD}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    mysql_data:

networks:
    financetracker_backend:
        driver: bridge
