spring:
    datasource:
        url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                "[format_sql]": true
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    port: 7777
    servlet:
      context-path: /api/v1

jwt:
    access-token-expiration: 600000
    refresh-token-expiration: 3600000
    public:
        key: classpath:app.pub
    private:
        key: classpath:app.key